name: ci

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:

  # Basic linting and tests.
  base-ci:

    runs-on: ubuntu-latest
    steps:

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y mecab mecab-ipadic-utf8

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt

    - name: Setup config
      run: |
        mkdir ./data
        echo "ENV: dev" > config/config.yml
        echo "DATAPATH: ./data" >> config/config.yml
        echo "DBNAME: test_lute.db" >> config/config.yml

    - name: Lint
      run: inv lint

    - name: Test
      run: pytest

    - name: Acceptance testing
      run: inv accept --headless -s
